- name: Packer
  hosts: 'all'
  become: yes
  become_method: sudo
  tasks:
    - name: install packages
      yum: name={{ item }} update_cache=yes state=latest
      with_items:
        - httpd
        - httpd-tools
        - mod_ssl
        - php
        - php-mysql
        - git


    - name: enable services
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: clone git repo
      git: repo=https://github.com/jorenknieper/CloudAndAutomation_Phase3_WebFiles.git dest=/cloudandautomation/ update=no

    - name: cp to var,www,html
      command: cp -r /cloudandautomation/www /var/
